kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: explorer-uc1-ibm-mq-qm
  namespace: ibm-mq
spec:
  host: app2e-svrconn.chl.mq.ibm.com
  to:
    kind: Service
    name: uc1-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
  wildcardPolicy: None
